; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
extra_configs = secret.ini


; ----------------Basement--------------------------------
; Basement door lock controller.
[c3-common]
extends = secret
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
build_src_filter = +<main_c3_relay_controller.cpp>
build_flags =
  ${secret.build_flags}
lib_deps = 
	knolleary/PubSubClient@^2.8
	adafruit/Adafruit BME280 Library@^2.3.0
	adafruit/Adafruit Unified Sensor@^1.1.15
	arduino-libraries/ArduinoBLE@^1.4.1

; Basement door lock mini-board, upload via USB.
[env:esp32-c3-relay-controller-usb]
extends = c3-common
lib_deps =
	${c3-common.lib_deps}
	adafruit/Adafruit PN532@^1.3.4

; Basement door lock mini-board remote upload via WiFi.
[env:esp32-c3-relay-controller-remote]
extends = c3-common
upload_port = 192.168.0.140
lib_deps =
	${c3-common.lib_deps}
	adafruit/Adafruit PN532@^1.3.4

; -----------------Chicken coop controller-------------------------

; This is chicken coop target.
[env:esp32-c3-chicken-coop]
extends = c3-common
build_src_filter = +<main_c3_chicken_coop_temp_amonia_sensor.cpp>
platform = espressif32
board = seeed_xiao_esp32c3 ; mini board
framework = arduino
build_unflags =
  -std=gnu++11
build_flags =
  ${secret.build_flags}
  -std=gnu++17
lib_deps = 
	${c3-common.lib_deps}
	adafruit/Adafruit PN532@^1.3.4


; This is chicken coop target.
[env:esp32-c3-chicken-coop-remote]
; extends = esp32-c3-chicken-coop
; ; upload_port = 192.168.0.110
; ; upload_protocol = espota
; upload_port = chicken.local

extends = c3-common
build_src_filter = +<main_c3_chicken_coop_temp_amonia_sensor.cpp>
platform = espressif32
board = seeed_xiao_esp32c3 ; mini board
framework = arduino
build_unflags =
  -std=gnu++11
build_flags =
  ${secret.build_flags}
  -std=gnu++17
lib_deps = 
	${c3-common.lib_deps}
	adafruit/Adafruit PN532@^1.3.4

; upload_port = 192.168.0.110
upload_protocol = espota
upload_port = chicken.local

;***************************************************
;-----------------------Sandbox-------------------------
; DEBUG BOARD
; the sandbox: change src filename to whihever you want to test in sandbox.
; This s3 sandbox target
[env:esp32-s3-devkitm-1-sandbox]
build_src_filter = +<tutorials/sandbox/s3_sb_http_server_dns.cpp>
; build_src_filter = +<tutorials/sandbox/s3_sb_asdf.cpp>
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
build_flags =
  ${secret.build_flags}
; lib_deps = 

;***************************************************
;------------------Tutorials-------------------------
; DEBUG BOARD
[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
build_src_filter = +<_example_main_ble.cpp>
build_flags =
  ${secret.build_flags}
lib_deps = 
	adafruit/Adafruit BME280 Library@^2.3.0
	adafruit/Adafruit Unified Sensor@^1.1.15
	adafruit/Adafruit NeoPixel@^1.15.1
	arduino-libraries/ArduinoBLE@^1.4.1
	adafruit/Adafruit PN532@^1.3.4

; [secret]
; build_flags = 
; 	-DWIFI_SSID=\"T-Mobile-Tom_bi_paulina_tomek\"
; 	-DWIFI_PASS=\"7FQR242857\"

; DEBUG BOARD
; RFID module
[env:esp32-s3-example-rfid-module-devkit-m1]
build_src_filter = +<tutorials/c3_rfid_module_task.cpp>
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
build_flags =
  ${secret.build_flags}
lib_deps = 
	adafruit/Adafruit PN532@^1.3.4
	adafruit/Adafruit NeoPixel@^1.15.1


; temperature sensor and mqtt tutorial
[env:esp32-c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
build_src_filter = +<tutorials/c3_mqtt_bme_sensor.cpp>
build_flags =
  ${secret.build_flags}
lib_deps = 
	knolleary/PubSubClient@^2.8
	adafruit/Adafruit NeoPixel@^1.15.1
	adafruit/Adafruit BME280 Library@^2.3.0
	adafruit/Adafruit Unified Sensor@^1.1.15
	ayushsharma82/WebSerial@^2.1.1
	adafruit/Adafruit PN532@^1.3.4

[env:native]
test_framework = googletest
platform = native
; framework = arduino
test_build_src = no

build_flags = -std=gnu++17
; lib_deps =
;   fabiobatsilva/ArduinoFake @ ^0.4.0
