
[secret]
build_flags =

  ; remember to update secrets.h, it it helps get rid of red underlines in the code editor
  -DSSID_OFFICE=\"ssid\"
  -DSSID_KITCHEN=\"ssid\"
  -DSSID_GARDEN=\"ssid\"
  -DWIFI_SSID=\"ssid\"
  -DWIFI_PASS=\"password\"