; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
extra_configs = secret.ini

[c3]
extends = secret
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
build_src_filter = +<main_c3_relay_controller.cpp>
build_unflags = 
	-std=gnu++11
build_flags = 
	${secret.build_flags}
	-std=gnu++17
lib_deps = 
	knolleary/PubSubClient@^2.8
	adafruit/Adafruit BME280 Library@^2.3.0
	adafruit/Adafruit Unified Sensor@^1.1.15
	arduino-libraries/ArduinoBLE@^1.4.1
	adafruit/Adafruit NeoPixel@^1.15.1
	adafruit/Adafruit PN532@^1.3.4
	adafruit/Adafruit AM2320 sensor library@^1.2.5

[s3]
extends = c3
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
build_unflags = 
	-std=gnu++11
build_flags = 
	${secret.build_flags}
	-std=gnu++17
lib_deps = 
	${c3.lib_deps}


[env:esp32-c3-relay-controller-usb]
extends = c3
build_src_filter = +<main_c3_relay_controller.cpp>

[env:esp32-c3-relay-controller-remote]
extends = c3
upload_port = relay.local
upload_protocol = espota
build_src_filter = +<main_c3_relay_controller.cpp>

[env:esp32-c3-chicken-coop]
extends = c3
build_src_filter = +<main_c3_chicken_coop_temp_amonia_sensor.cpp>

[env:esp32-c3-chicken-coop-remote]
extends = env:esp32-c3-chicken-coop
upload_port = chicken.local
upload_protocol = espota

[env:esp32-s3-devkitm-1-sandbox]
extends = s3
build_src_filter = +<tutorials/sandbox/s3_sb_http_server_dns.cpp>

[env:esp32-s3-devkitm-1-am2320-example]
extends = s3
build_src_filter = +<tutorials/am2320_ex.cpp>
lib_ignore =
	chicken_coop
	relay_controller
lib_deps = 
	${s3.lib_deps}
	adafruit/Adafruit AM2320 sensor library@^1.2.5

; [env:esp32-s3-example-rfid-module-devkit-m1]
; extends = s3
; build_src_filter = +<tutorials/c3_rfid_module_task.cpp>

[env:native]
test_framework = googletest
platform = native
test_build_src = no
build_flags = -std=gnu++17
