; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
extra_configs = secret.ini

[c3-common]
extends = secret
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
build_src_filter = +<main_c3_relay_controller.cpp>
build_unflags = 
	-std=gnu++11
build_flags = 
	${secret.build_flags}
	-std=gnu++17
lib_deps = 
	knolleary/PubSubClient@^2.8
	adafruit/Adafruit BME280 Library@^2.3.0
	adafruit/Adafruit Unified Sensor@^1.1.15
	arduino-libraries/ArduinoBLE@^1.4.1
	adafruit/Adafruit NeoPixel@^1.15.1
	adafruit/Adafruit PN532@^1.3.4

[env:esp32-c3-relay-controller-usb]
extends = c3-common
lib_deps = 
	robtillaart/AM232X@^0.5.3
	adafruit/Adafruit AM2320 sensor library@^1.2.5

[env:esp32-c3-relay-controller-remote]
extends = c3-common
upload_port = 192.168.0.140
lib_deps = 
	robtillaart/AM232X@^0.5.3
	adafruit/Adafruit AM2320 sensor library@^1.2.5

[env:esp32-c3-chicken-coop]
extends = c3-common
build_src_filter = +<main_c3_chicken_coop_temp_amonia_sensor.cpp>
lib_deps = 
	robtillaart/AM232X@^0.5.3
	adafruit/Adafruit AM2320 sensor library@^1.2.5

[env:esp32-c3-chicken-coop-remote]
extends = env:esp32-c3-chicken-coop
upload_protocol = espota
upload_port = chicken.local
lib_deps = 
	robtillaart/AM232X@^0.5.3
	adafruit/Adafruit AM2320 sensor library@^1.2.5

[env:esp32-s3-devkitm-1-sandbox]
build_src_filter = +<tutorials/sandbox/s3_sb_http_server_dns.cpp>
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
build_flags = 
	${secret.build_flags}
lib_deps = 
	robtillaart/AM232X@^0.5.3
	adafruit/Adafruit AM2320 sensor library@^1.2.5

[env:esp32-s3-devkitm-1-tutorials]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
build_src_filter = +<tutorials/s3_basic_setup_ble.cpp>
build_flags = 
	${secret.build_flags}
lib_deps = 
	adafruit/Adafruit NeoPixel@^1.15.1
	arduino-libraries/ArduinoBLE@^1.4.1
	robtillaart/AM232X@^0.5.3
	adafruit/Adafruit AM2320 sensor library@^1.2.5

[env:esp32-s3-example-rfid-module-devkit-m1]
build_src_filter = +<tutorials/c3_rfid_module_task.cpp>
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
build_flags = 
	${secret.build_flags}
lib_deps = 
	adafruit/Adafruit PN532@^1.3.4
	adafruit/Adafruit NeoPixel@^1.15.1
	robtillaart/AM232X@^0.5.3
	adafruit/Adafruit AM2320 sensor library@^1.2.5

[env:esp32-c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
build_src_filter = +<tutorials/c3_mqtt_bme_sensor.cpp>
build_flags = 
	${secret.build_flags}
lib_deps = 
	knolleary/PubSubClient@^2.8
	adafruit/Adafruit NeoPixel@^1.15.1
	adafruit/Adafruit BME280 Library@^2.3.0
	adafruit/Adafruit Unified Sensor@^1.1.15
	ayushsharma82/WebSerial@^2.1.1
	adafruit/Adafruit PN532@^1.3.4
	robtillaart/AM232X@^0.5.3
	adafruit/Adafruit AM2320 sensor library@^1.2.5

[env:native]
test_framework = googletest
platform = native
test_build_src = no
build_flags = -std=gnu++17
lib_deps = 
	robtillaart/AM232X@^0.5.3
	adafruit/Adafruit AM2320 sensor library@^1.2.5
