
[secret]
build_flags =

  ; remember to update secrets.h, it it helps get rid of red underlines in the code editor
  -DSSID_OFFICE=\"ssid\"
  -DSSID_KITCHEN=\"ssid\"
  -DSSID_GARDEN=\"ssid\"
  -DWIFI_SSID=\"ssid\"
  -DWIFI_PASS=\"password\"
  -DMQTT_USER=\"\"
  -DMQTT_PASS=\"\"
  -DDOOR_TOKEN=\"\"
  -DBLE_DOOR_PASS=\"\"

# TODO
  -DURL_BASEMENT=\"basement.local\"
  -DURL_COOP=\"coop.local\"
