[project]
name = "py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiomqtt>=2.5.1",
    "aiosqlite>=0.22.1",
    "fastapi>=0.136.0",
    "greenlet>=3.4.0",
    "icecream>=2.1.10",
    "ipdb>=0.13.13",
    "ipython>=9.11.0",
    "loguru>=0.7.3",
    "netifaces>=0.11.0",
    "paho-mqtt>=2.1.0",
    "pydantic>=2.13.2",
    "sqlalchemy>=2.0.49",
    "typer>=0.24.1",
    "uvicorn>=0.44.0",
    "zeroconf>=0.148.0",
]
