[project]
name = "py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "icecream>=2.1.10",
    "ipdb>=0.13.13",
    "ipython>=9.11.0",
    "loguru>=0.7.3",
    "netifaces>=0.11.0",
    "typer>=0.24.1",
    "zeroconf>=0.148.0",
]
