[c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
build_src_filter = +<main_c3_relay_controller.cpp>
build_unflags = 
	-std=gnu++11
build_flags = 
	-std=gnu++17

[s3]
extends = c3
board = esp32-s3-devkitm-1


[env:s3-main]
extends = s3
build_src_filter = +<main.cpp>
lib_deps = 
    WiFiConn=symlink://../../libraries/wifi_conn
	Utilities=symlink://../../libraries/common
	; adafruit/Adafruit GFX Library
    ; adafruit/Adafruit SSD1306
	; adafruit/Adafruit AM2320 sensor library@^1.2.5