; [env:s3-modern]
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
; board = esp32-s3-devkitm-1
; framework = arduino

; build_flags =
;     -std=gnu++23

[c3]
; platform = espressif32
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = seeed_xiao_esp32c3
framework = arduino
build_src_filter = +<main_c3_relay_controller.cpp>
build_unflags = 
	-std=gnu++11
	; -std=gnu++17
; build_flags =
    ; -std=gnu++23
build_flags = 
	-std=gnu++17

[s3]
extends = c3
board = esp32-s3-devkitm-1


[env:s3-main]
extends = s3
build_src_filter = +<main.cpp>
lib_deps = 
    WiFiConn=symlink://../../libraries/wifi_conn
	Utilities=symlink://../../libraries/common
	MyAM2320=symlink://../../libraries/my_am2320
	; adafruit/Adafruit GFX Library
    ; adafruit/Adafruit SSD1306
	; adafruit/Adafruit AM2320 sensor library@^1.2.5