version: '3'

tasks:
  build:
    desc: Build the project
    vars:
      TARGET: '{{default "s3-main" .TARGET}}'
    cmds:
      - echo "Building the project..."
      - pio run -e {{.TARGET}}

  upload:
    desc: Upload the project
    cmds:
      - echo "Uploading the project..."
      - pio run -t upload

  upload_and_monitor:
    desc: Upload the project and monitor the project
    cmds:
      - echo "Uploading the project and monitoring the project..."
      - pio run -t upload -t monitor

  monitor:
    desc: Upload the project and monitor the project
    cmds:
      - echo "Monitoring..."
      - pio run -t monitor
